#!/usr/bin/env bash

# Detect if script is being sourced
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  __ACTIVATE_SOURCED=1
else
  __ACTIVATE_SOURCED=0
fi

# Use strict mode only when executed, not when sourced
if [[ "${__ACTIVATE_SOURCED}" -eq 0 ]]; then
  set -euo pipefail
fi

# Auto-detect or reuse PROJECT_ID
PROJECT_ID="${PROJECT_ID:-$(gcloud config get-value core/project 2>/dev/null || true)}"
if [[ -z "${PROJECT_ID}" || "${PROJECT_ID}" == "(unset)" ]]; then
  echo "ERROR: PROJECT_ID is not set. Run: export PROJECT_ID=<your-project-id>" >&2
  if [[ "${__ACTIVATE_SOURCED}" -eq 1 ]]; then
    return 1
  else
    exit 1
  fi
fi
export PROJECT_ID

# Dataset and model configuration
export BQ_DATASET="${BQ_DATASET:-demo_diabetes}"
export BQ_LOCATION="${BQ_LOCATION:-US}"
export GCS_URI="${GCS_URI:-gs://class-demo/diabetes_prediction_dataset.csv}"

# Table
export RAW_TABLE="${BQ_DATASET}.diabetes_raw"

# --- Model and Agent Runtime settings ---
#
# Two different locations, on purpose:
#   GEMINI_LOCATION  where the MODEL is called. The current Gemini models are
#                    served from "global", so this is not a region.
#   AGENT_REGION     where the AGENT is deployed. Agent Runtime needs a real
#                    region - "global" is not valid here.
export GEMINI_LOCATION="${GEMINI_LOCATION:-global}"
export AGENT_REGION="${AGENT_REGION:-us-central1}"
export AGENT_MODEL="${AGENT_MODEL:-gemini-flash-latest}"
export AGENT_DISPLAY_NAME="${AGENT_DISPLAY_NAME:-Diabetes Risk Agent}"

# NOTE: `adk deploy agent_engine` no longer uses a staging bucket
# (--staging_bucket is deprecated in ADK 2.x). GCS_URI above is still used to
# load the training CSV into BigQuery.
export STAGING_BUCKET="${STAGING_BUCKET:-gs://class-demo}"

# Write the agent's .env so that `adk web` locally and `adk deploy agent_engine`
# both see the same project. The deploy reads this file and turns it into the
# deployed agent's environment variables, which is how PROJECT_ID reaches the
# agent once it is running in Agent Runtime.
__DEMO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]:-$0}" )" && pwd )"
if [[ -d "${__DEMO_ROOT}/diabetes_agent" ]]; then
  cat > "${__DEMO_ROOT}/diabetes_agent/.env" <<ENVEOF
# Generated by activate.sh - do not edit by hand.
# GOOGLE_CLOUD_LOCATION is where the MODEL is served (global), not where the
# agent is deployed. 4_deploy.sh passes the deployment region explicitly.
GOOGLE_GENAI_USE_ENTERPRISE=1
GOOGLE_CLOUD_PROJECT=${PROJECT_ID}
GOOGLE_CLOUD_LOCATION=${GEMINI_LOCATION}
PROJECT_ID=${PROJECT_ID}
BQ_DATASET=${BQ_DATASET}
AGENT_MODEL=${AGENT_MODEL}
ENVEOF
  echo "✓ Wrote diabetes_agent/.env"
fi

echo "✓ Environment configured:"
echo "  PROJECT_ID:      ${PROJECT_ID}"
echo "  DATASET:         ${BQ_DATASET}"
echo "  BQ LOCATION:     ${BQ_LOCATION}"
echo "  MODEL:           ${AGENT_MODEL}"
echo "  MODEL LOCATION:  ${GEMINI_LOCATION}   (where Gemini is called)"
echo "  DEPLOY REGION:   ${AGENT_REGION}   (where the agent is hosted)"
echo ""
echo "Ready to proceed with demo setup!"
